#include "LevelSerializer.hpp"
#include <filesystem>
#include <ctime>
#include <iomanip>

std::string LevelSerializer::GetLevelsDirectory()
{
	return "Levels/";
}

std::string LevelSerializer::CreateFilename(const std::string& levelName)
{
	std::string filename = levelName;

	//Replace spaces and special characters with underscores
	for (char& c : filename)
	{
		if (!std::isalnum(c))
			c = '_';
	}

	return GetLevelsDirectory() + "level_" + filename + ".lvl";
}

bool LevelSerializer::Save(const LevelData& level, const std::string& filename)
{
	//Create Levels directory if it doesn't exist
	std::filesystem::create_directories(GetLevelsDirectory());

	std::ofstream file(filename);
	if (!file.is_open())
	{
		std::cerr << "Failed to open file for writing: " << filename << std::endl;
		return false;
	}

	//Write header
	file << "# Level File Format v1.0\n";
	file << "# Generated by Level Editor\n\n";

	//Write metadata
	file << "[METADATA]\n";
	file << "LevelName=" << level.m_metadata.m_level_name << "\n";
	file << "CreationDate=" << level.m_metadata.m_creation_date << "\n";
	file << "Author=" << level.m_metadata.m_author << "\n";
	file << "GridSize=" << level.m_metadata.m_grid_size << "\n\n";

	//Write world bounds
	file << "[WORLD_BOUNDS]\n";
	file << "Left=" << level.m_world_bounds.position.x << "\n";
	file << "Top=" << level.m_world_bounds.position.y << "\n";
	file << "Width=" << level.m_world_bounds.size.x << "\n";
	file << "Height=" << level.m_world_bounds.size.y << "\n\n";

	//Write tiles
	file << "[TILES]\n";
	file << "Count=" << level.m_tiles.size() << "\n";
	for (const auto& tile : level.m_tiles)
	{
		file << TileTypeToString(tile.m_type) << ","
			<< tile.m_position.x << ","
			<< tile.m_position.y << ","
			<< tile.m_texture_variant << ","
			<< tile.m_width << ","
			<< tile.m_height << "\n";
	}
	file << "\n";

	//Write player spawns
	file << "[PLAYER_SPAWNS]\n";
	file << "Count=" << level.m_player_spawns.size() << "\n";
	for (const auto& spawn : level.m_player_spawns)
	{
		file << spawn.m_spawn_index << ","
			<< spawn.m_position.x << ","
			<< spawn.m_position.y << "\n";
	}

	file.close();
	return true;
}

bool LevelSerializer::Load(const std::string& filename, LevelData& level)
{
	std::ifstream file(filename);
	if (!file.is_open())
	{
		std::cerr << "Failed to open file for reading: " << filename << std::endl;
		return false;
	}

	level.Clear();
	std::string line;
	std::string currentSection;

	while (std::getline(file, line))
	{
		//Skip comments and empty lines
		if (line.empty() || line[0] == '#')
			continue;

		//Check for section headers
		if (line[0] == '[')
		{
			currentSection = line;
			continue;
		}

		//Parse based on current section
		if (currentSection == "[METADATA]")
		{
			size_t pos = line.find('=');
			if (pos != std::string::npos)
			{
				std::string key = line.substr(0, pos);
				std::string value = line.substr(pos + 1);

				if (key == "LevelName")
					level.m_metadata.m_level_name = value;
				else if (key == "CreationDate")
					level.m_metadata.m_creation_date = value;
				else if (key == "Author")
					level.m_metadata.m_author = value;
				else if (key == "GridSize")
					level.m_metadata.m_grid_size = std::stoi(value);
			}
		}
		else if (currentSection == "[WORLD_BOUNDS]")
		{
			size_t pos = line.find('=');
			if (pos != std::string::npos)
			{
				std::string key = line.substr(0, pos);
				std::string value = line.substr(pos + 1);

				if (key == "Left")
					level.m_world_bounds.position.x = std::stof(value);
				else if (key == "Top")
					level.m_world_bounds.position.y = std::stof(value);
				else if (key == "Width")
					level.m_world_bounds.size.x = std::stof(value);
				else if (key == "Height")
					level.m_world_bounds.size.y = std::stof(value);
			}
		}
		else if (currentSection == "[TILES]")
		{
			if (line.find("Count=") == 0)
				continue;

			//Parse tile data: Type,X,Y,Variant,Width,Height
			std::stringstream ss(line);
			std::string typeStr, xStr, yStr, variantStr, widthStr, heightStr;

			std::getline(ss, typeStr, ',');
			std::getline(ss, xStr, ',');
			std::getline(ss, yStr, ',');
			std::getline(ss, variantStr, ',');
			std::getline(ss, widthStr, ',');
			std::getline(ss, heightStr, ',');

			TileData tile;
			tile.m_type = StringToTileType(typeStr);
			tile.m_position.x = std::stof(xStr);
			tile.m_position.y = std::stof(yStr);
			tile.m_texture_variant = std::stoi(variantStr);
			tile.m_width = std::stof(widthStr);
			tile.m_height = std::stof(heightStr);

			level.m_tiles.push_back(tile);
		}
		else if (currentSection == "[PLAYER_SPAWNS]")
		{
			if (line.find("Count=") == 0)
				continue;

			//Parse spawn data: Index,X,Y
			std::stringstream ss(line);
			std::string indexStr, xStr, yStr;

			std::getline(ss, indexStr, ',');
			std::getline(ss, xStr, ',');
			std::getline(ss, yStr, ',');

			PlayerSpawnData spawn;
			spawn.m_spawn_index = std::stoi(indexStr);
			spawn.m_position.x = std::stof(xStr);
			spawn.m_position.y = std::stof(yStr);

			level.m_player_spawns.push_back(spawn);
		}
	}

	file.close();
	return level.IsValid();
}

std::string LevelSerializer::TileTypeToString(TileType type)
{
	switch (type)
	{
	case TileType::kNone:
		return "None";
	case TileType::kPlatform:
		return "Platform";
	case TileType::kBox:
		return "Box";
	case TileType::kPlayerSpawn:
		return "PlayerSpawn";
	default:
		return "Unknown";
	}
}

TileType LevelSerializer::StringToTileType(const std::string& str)
{
	if (str == "None")
		return TileType::kNone;
	if (str == "Platform")
		return TileType::kPlatform;
	if (str == "Box")
		return TileType::kBox;
	if (str == "PlayerSpawn")
		return TileType::kPlayerSpawn;

	return TileType::kNone;
}